### ISSUE TITLE
Split out Usage into Usage and Commands (matching commander.js)

### ISSUE THREAD

**Issue by BigBlueHat** [docopt/docopt.org#10]
There's a very similar project in the node.js/npm world called [commander.js](http://visionmedia.github.io/commander.js/). It's format looks similar:

Here's [component.io](http://component.io/)'s command line client's output:

```
  Usage: component <command> [options]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

  Commands:

    install [name ...]      install one or more components
    create [dir]            create a component skeleton
    search [query]          search with the given query
    convert <file ...>      convert html files to js modules
    info <name> [prop]      output json component information
    changes <name>          output changelog contents
    wiki                    open the components list wiki page
    build                   build the component
    ls                      list installed components
```

It's _extremely_ similar.

Many command line scripts generate a "Usage" line at the beginning that matches that format, and having the name of the script out of the "Commands" section would make the experience simpler and tighter in general.

Thanks for considering this! If there's a better repo to put these requests/ideas, I'm happy to refile it. :smiley:

**Comment by fsaintjacques** [comment]
I believe this introduce a lot of parsing ambiguity due to the help text, but I like the idea.

**Comment by keleshev** [comment]
Sorry for late response. You can do something very similar to this already. This is a valid docopt usage:

``` docopt
  Usage: component <command> [options]

  Options:
    -h, --help     output usage information
    -V, --version  output the version number

  Commands:
    install [name ...]      install one or more components
    create [dir]            create a component skeleton
    search [query]          search with the given query
    convert <file ...>      convert html files to js modules
    info <name> [prop]      output json component information
    changes <name>          output changelog contents
    wiki                    open the components list wiki page
    build                   build the component
    ls                      list installed components
```

However, commands-section will be ignored. This is fine, because each of the subcommands (like `component install`) should have it's own usage anyway. For example of interfaces with multiple subcommands, each having its own usage see:

https://github.com/docopt/docopt/tree/master/examples/git

**Comment by BigBlueHat** [comment]
Fabulous! Great to know, thanks. :smile_cat:
