### ISSUE TITLE
Webpage does not have a (properly formatted) printable version

### ISSUE THREAD

**Issue by ffunenga** [docopt/docopt.org#3]
When you press "File">"Print..." on your web-browser (obviously, depends on the web-browser), the webpage is not configured to a printable version. This is more like a "Feature Request".

IMO, the idea of having a single webpage which is the index.html and, at the same time, the tutorial/api is great. If it could have a (properly formatted) printable version, it would be even better!

**Comment by keleshev** [comment]
What is missing? In Chrome it looks more or less ok. Maybe you can send a pull-request?
